/*
 * Modernizr is built from a declared feature list, and nothing reads a detect that is not declared.
 *
 * This file exists because of what the git history of wwwroot/assets/js/modernizr-custom.js showed.
 * It was generated by hand on modernizr.com and pasted in, so its feature set drifted 16 -> 26 -> 20
 * -> 27 detects over two years, one commit silently dropped seven of them, and the version banner
 * flip-flopped between 3.12.0 and 3.13.1 depending on who committed last (the code was identical --
 * that churn was pure diff noise). Nothing recorded what the site actually needed.
 *
 * The failure that matters is silent in the way this suite keeps finding: Modernizr writes a class
 * per detect onto <html>, and screen.css gives .grid--flex its `display: flex` ONLY under
 * `.flexbox`. There is no .no-flexbox fallback. Drop that detect and every flex grid on the site
 * quietly becomes a block layout -- no error, no build failure, nothing in the console.
 *
 * So the assertions run in both directions: the declared list must cover everything the code reads,
 * and the three detects known to be load-bearing must stay declared.
 *
 * Proven able to fail: deleting 'test/css/flexbox' from the config fails the CSS drift guard naming
 * screen.css; adding `Modernizr.webgl` to a view fails the JS guard naming the file; changing the
 * config's detect count without rebuilding fails the banner check.
 */

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

import { JSDOM } from 'jsdom';

import * as assert from './_assert.js';
import { ASSETS, SITES } from '../paths.mjs';
import { stripComments } from './_source.js';

const require = createRequire(import.meta.url);

console.log('modernizr -- built from a declared list, and nothing reads an undeclared detect');

const CONFIG_REL = 'nursingworld/js/modernizr.config.mjs';
const CONFIG_PATH = path.join(SITES, CONFIG_REL);
const OUTPUT = path.join(ASSETS, 'js/modernizr-custom.js');

const mod = await import(`file://${CONFIG_PATH}`);
const config = mod.default;
const CONSUMED = mod.CONSUMED;

// --- the config is well formed -----------------------------------------------------------------

const detects = config['feature-detects'];

assert.ok(Array.isArray(detects) && detects.length > 0,
    `the config declares a feature-detect list (${detects.length} detects)`);

assert.equal(new Set(detects).size, detects.length,
    'no detect is declared twice');

assert.ok(config.options.includes('setClasses'),
    'setClasses is enabled -- without it Modernizr writes no <html> classes at all, ' +
    'which is the whole mechanism screen.css depends on');

/*
 * _Base.cshtml:26 renders <html class="no-js">. Modernizr's enableJSClass swaps it to "js". Nothing
 * else performs that swap, so it is part of the contract between the layout and this file.
 */
assert.ok(config.options.includes('addTest') && config.options.includes('testProp'),
    'the helper options the detects compile against are declared');

// --- every detect name resolves to a real Modernizr detect ---------------------------------------

/*
 * A typo here would not fail the build -- modernizr skips what it cannot resolve -- it would just
 * silently ship one fewer detect. Which is the exact failure mode this whole file is about.
 */
const metaByPath = new Map();
const propToPath = new Map();

await new Promise((resolve) => {
    require('modernizr').metadata((meta) => {
        for (const d of meta) {
            if (d.amdPath) metaByPath.set(d.amdPath, d);

            for (const p of [].concat(d.property ?? [])) {
                propToPath.set(String(p).toLowerCase(), d.amdPath);
            }
        }

        resolve();
    });
});

assert.ok(propToPath.size > 300,
    `the Modernizr vocabulary loaded (${propToPath.size} known properties)`);

const unknown = detects.filter((d) => !metaByPath.has(d));

assert.equal(unknown.length, 0,
    'every declared detect resolves to a real Modernizr detect' +
    (unknown.length ? ': ' + unknown.join(', ') : ''));

/* The property names those detects produce -- what code would actually read. */
const declaredProps = new Set();

for (const d of detects) {
    for (const p of [].concat(metaByPath.get(d).property ?? [])) declaredProps.add(String(p).toLowerCase());
}

// --- the known consumers stay declared -----------------------------------------------------------

for (const [prop, why] of Object.entries(CONSUMED)) {
    assert.ok(declaredProps.has(prop),
        `${prop} is still declared -- ${why.slice(0, 70)}…`);
}

// --- drift guard 1: compiled CSS ------------------------------------------------------------------

/*
 * Modernizr classes are always ANCESTORS (`.flexbox .grid--flex`), never the styled element itself,
 * so the combinator is what separates a real usage from a component that happens to be called
 * .details or .hidden. Scanned against the full 322-property vocabulary rather than the declared
 * list, because the point is to catch a detect being USED that is NOT declared.
 */
function cssFiles(dir, out = []) {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, e.name);

        if (e.isDirectory()) cssFiles(full, out);
        else if (e.name.endsWith('.css')) out.push(full);
    }

    return out;
}

const stylesheets = cssFiles(ASSETS);

assert.ok(stylesheets.length > 5, `scanning the compiled stylesheets (${stylesheets.length})`);

const cssUsed = new Map();

for (const file of stylesheets) {
    const text = fs.readFileSync(file, 'utf8');

    for (const prop of propToPath.keys()) {
        const re = new RegExp(`\\.(no-)?${prop.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?=[\\s>])`);

        if (re.test(text)) {
            cssUsed.set(prop, (cssUsed.get(prop) ?? []).concat(path.basename(file)));
        }
    }
}

assert.ok(cssUsed.has('flexbox'),
    'the CSS scan still finds .flexbox -- without this the next assertion proves nothing');

const cssUndeclared = [...cssUsed].filter(([p]) => !declaredProps.has(p));

assert.equal(cssUndeclared.length, 0,
    'every Modernizr class the compiled CSS styles against is a declared detect' +
    (cssUndeclared.length
        ? ':\n  ' + cssUndeclared.map(([p, f]) => `.${p} used in ${[...new Set(f)].join(', ')} — add its detect to ${CONFIG_REL}`).join('\n  ')
        : ` (${cssUsed.size} used, ${declaredProps.size} declared)`));

// --- drift guard 2: JS source ---------------------------------------------------------------------

function jsFiles(dir, out = []) {
    if (!fs.existsSync(dir)) return out;

    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, e.name);

        if (e.isDirectory()) { if (e.name !== 'vendor' && e.name !== 'lib') jsFiles(full, out); }
        else if (e.name.endsWith('.js')) out.push(full);
    }

    return out;
}

const sources = jsFiles(SITES);

assert.ok(sources.length > 150, `scanning the site source (${sources.length} files)`);

const jsUsed = new Map();

for (const file of sources) {
    const text = stripComments(fs.readFileSync(file, 'utf8'));

    for (const m of text.matchAll(/\bModernizr\.([a-zA-Z0-9_]+)/g)) {
        const prop = m[1].toLowerCase();

        // Internals (_version, _config) and the helpers, not detects.
        if (prop.startsWith('_') || ['addtest', 'on', 'prefixed'].includes(prop)) continue;

        jsUsed.set(prop, (jsUsed.get(prop) ?? []).concat(
            `${path.relative(SITES, file).split(path.sep).join('/')}:${text.slice(0, m.index).split('\n').length}`
        ));
    }
}

assert.ok(jsUsed.has('objectfit') && jsUsed.has('requestanimationframe'),
    `the JS scan still finds the known reads (${[...jsUsed.keys()].sort().join(', ')})`);

const jsUndeclared = [...jsUsed].filter(([p]) => !declaredProps.has(p));

assert.equal(jsUndeclared.length, 0,
    'every Modernizr detect the source reads is declared in the config' +
    (jsUndeclared.length
        ? ':\n  ' + jsUndeclared.map(([p, w]) => `Modernizr.${p} read at ${w.join(', ')} — add its detect to ${CONFIG_REL}`).join('\n  ')
        : ''));

// --- the built output matches the config ----------------------------------------------------------

assert.ok(fs.existsSync(OUTPUT), 'the build produced js/modernizr-custom.js');

const built = fs.readFileSync(OUTPUT, 'utf8');

const banner = /^\/\*! modernizr v([\d.]+) \| (\d+) detects \| built from (\S+) \|/.exec(built);

assert.ok(banner, 'the output carries the generated banner, so what shipped is traceable to a config');

assert.equal(Number(banner[2]), detects.length,
    `the banner's detect count matches the config (${banner?.[2]} vs ${detects.length}) — ` +
    'a mismatch means wwwroot was not rebuilt after the config changed');

assert.equal(banner[3], 'js/modernizr.config.mjs',
    'and names the config it was built from');

/*
 * The per-detect /*! ... !*\/ metadata blocks Modernizr emits are 8.2KB minified on a script every
 * page loads blocking. Stripping them is deliberate; this keeps them stripped.
 */
assert.equal((built.match(/\/\*!/g) ?? []).length, 1,
    'only the one banner comment survives — the 24 per-detect metadata blocks are stripped');

assert.ok(built.length < 16 * 1024,
    `the output stays smaller than the hand-built file it replaced (${built.length} vs 14126 bytes)`);

// --- it actually works ----------------------------------------------------------------------------

/*
 * Booted the way _Base.cshtml does it: a classic script against <html class="no-js">. Asserting the
 * classes rather than just the object, because the classes are what screen.css consumes.
 */
const dom = new JSDOM('<!doctype html><html class="no-js"></html>', {
    runScripts: 'outside-only', pretendToBeVisual: true,
});

// Every browser this site supports has CSS.supports; jsdom does not, and without it Modernizr falls
// through to a prefix-probing path no real browser takes.
dom.window.CSS = { supports: (p) => ['transform', 'animation-name', 'transition', 'perspective', 'flex-basis', 'object-fit'].includes(p) };

dom.window.eval(built);

const M = dom.window.Modernizr;
const classes = dom.window.document.documentElement.className.split(/\s+/).filter(Boolean);

assert.equal(M._version, '3.13.1', 'the booted build reports its version');

assert.ok(classes.includes('js') && !classes.includes('no-js'),
    'the no-js → js swap _Base.cshtml:26 depends on still happens');

assert.ok(classes.length > 25,
    `it writes a class per detect onto <html> (${classes.length} classes)`);

for (const prop of Object.keys(CONSUMED)) {
    assert.ok(typeof M[prop] === 'boolean' || M[prop] instanceof Boolean,
        `Modernizr.${prop} is defined after boot, so its consumer reads a real value`);
}

assert.done();
