// ─── Modernizr build ─────────────────────────────────────────────────────────
//
// Modernizr is served on EVERY page of both properties — BundleInitialization.cs
// registers /bundles/moderniz, and _Base.cshtml:90 and _HubRoot.cshtml:88 both
// load it as a blocking classic script ahead of entry.js.
//
// It used to be generated by hand on modernizr.com and the result pasted into
// wwwroot. Nothing recorded which detects the site needed or why, and the git
// history shows exactly what that costs: the feature set drifted 16 → 26 → 20 →
// 27 detects across two years, and one commit (326600490, 2025-06-06) silently
// dropped seven of them with no stated reason. The banner also flip-flopped
// between 3.12.0 and 3.13.1 depending on who committed last — the generated code
// was byte-identical, so that churn was pure noise in the diff.
//
// This file is now the source of truth, and scripts/modernizr.mjs builds the
// output from it. Changing the deployed Modernizr means editing this list.
//
// ── Which detects are actually used ──
//
// Only THREE of the 22 are read by anything in this repo. The other 19 are
// retained deliberately rather than trimmed: every detect also writes a class
// onto <html>, and CMS-authored content and inline styles are outside this
// repo's view, so dropping one is a product decision with a visible blast
// radius — not a build cleanup. test/modernizr.test.js asserts the three below
// stay present, and fails if code starts reading a fourth that is not declared.

export const CONSUMED = {
    flexbox: 'scss/base/_base-layout.scss:70 — `.flexbox .grid--flex` is the ONLY '
        + 'thing that gives .grid--flex `display: flex`. There is no .no-flexbox '
        + 'fallback, so without this class every flex grid silently becomes block.',
    objectfit: 'js/src/components/object-fit-polyfill.js:35 — gates the polyfill.',
    requestanimationframe: 'js/src/views/view-more-view.js:156 — picks rAF over setTimeout.',
};

export default {
    // Options, not detects. addTest/testProp are the public helpers the detects
    // themselves compile against; setClasses is what writes the <html> classes
    // that the flexbox rule above depends on, and also performs the no-js → js
    // swap that _Base.cshtml:26 renders `class="no-js"` expecting.
    options: ['addTest', 'fnBind', 'html5printshiv', 'setClasses', 'testProp'],

    // Exactly the 22 detects the hand-built file shipped, so this build is a
    // like-for-like replacement. Verified equivalent at runtime — see the test.
    'feature-detects': [
        'test/css/animations',
        'test/css/checked',
        'test/css/flexbox',              // CONSUMED — see above
        'test/css/gradients',
        'test/css/objectfit',            // CONSUMED — see above
        'test/css/pointerevents',
        'test/css/target',
        'test/css/transforms',
        'test/css/transforms3d',
        'test/css/transitions',
        'test/dom/hidden',
        'test/elem/details',
        'test/elem/time',
        'test/es6/contains',
        'test/img/sizes',
        'test/img/srcset',
        'test/json',
        'test/network/fetch',
        'test/proxy',
        'test/requestanimationframe',    // CONSUMED — see above
        'test/svg',
        'test/video',
    ],
};
